### ISSUE TITLE
Redo Team Salary Pie Chart

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/parity-server#127]
related to #53 

The current pie chart is written in [d3.js](https://d3js.org/) a low level library for creating graphs and other svg (scalable vector graphics) based visualisations. There are many readily available and high quality graphing tools built on top of d3 which would give a better result and be simpler than the current graphing code. There are also a few issues with the current graph like #116 

**ToDo**:
- [ ] remove the code that renders the old graph:
*  https://github.com/kevinhughes27/parity-server/blob/master/client/src/Components/TeamDashboard/index.js#L49-L55
* https://github.com/kevinhughes27/parity-server/blob/master/client/src/Components/TeamDashboard/index.js#L46
* https://github.com/kevinhughes27/parity-server/blob/master/client/src/Components/TeamDashboard/index.js#L57-L60
* https://github.com/kevinhughes27/parity-server/blob/master/client/src/Components/TeamDashboard/index.js#L45-L47
- [ ]  Replace this code here with a new graph component https://github.com/kevinhughes27/parity-server/blob/master/client/src/Components/TeamDashboard/index.js#L142 from https://github.com/reactjs/react-chartjs
- [ ] Test that it works by visiting http://localhost:3000/team_dashboard
